/**
 *
 */
package org.jabsorb.client.async;

import java.lang.reflect.Method;
import java.util.concurrent.Future;

/**
 * <p>This interface is implemented by proxies genereted with
 * {@link AsyncClient#openProxy(String, Class)}. Its InvocationHandler provides
 * the required functionality.
 * </p>
 * <p>
 * The methods of this interface provide a means to get and act upon results
 * from asynchronous proxies generated by AscyncClient, which always return null
 * immediately.
 * </p>
 * <p>
 * You can check wether some proxy object implements this intereface using
 * <code>instanceof</code>
 * </p>
 *
 * @author matthijs
 */
public interface AsyncProxy {
	public Future<Object> getFutureResult();

	public void setResultCallback(AsyncResultCallback<Object, Object, Method> resultCallback);
}
