/*
 * jabsorb - a Java to JavaScript Advanced Object Request Broker
 * http://www.jabsorb.org
 *
 * Copyright 2007-2009 The jabsorb team
 *
 * based on original code from
 * JSON-RPC-Java - a JSON-RPC to Java Bridge with dynamic invocation
 *
 * Copyright Metaparadigm Pte. Ltd. 2004.
 * Michael Clark <michael@metaparadigm.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 */
package org.jabsorb.client.async;

import java.lang.reflect.Method;
import java.util.concurrent.Future;

/**
 * <p>
 * This interface is implemented by proxies genereted with
 * {@link AsyncClient#openProxy(String, Class)}. Its InvocationHandler provides the required
 * functionality.
 * </p>
 * <p>
 * The methods of this interface provide a means to get and act upon results from asynchronous
 * proxies generated by AscyncClient, which always return null immediately.
 * </p>
 * <p>
 * You can check wether some proxy object implements this intereface using <code>instanceof</code>
 * </p>
 *
 * @author matthijs
 */
public interface AsyncProxy {
  public Future<Object> getFutureResult();

  public void setResultCallback(AsyncResultCallback<Object, Object, Method> resultCallback);
}
