runtime: java17
entrypoint: java -jar dumbo-jacline-helloworld-1.0.0-main.jar
handlers:
- url: /hello
  static_dir: static/hello
- url: /(.*\.(txt|html|css|js|map|gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(txt|html|css|js|map|gif|png|jpg)$
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

env_variables:
  DUMBO_CONTENT_SOURCE: "."
